### ISSUE TITLE
pathway to mirna mappings

### ISSUE THREAD

**Issue by ariutta** [ariutta/mirna-pathway-finder#1]
@AlexanderPico, here is a dummy file to hold the sample mappings you mentioned:
https://github.com/ariutta/mirna-pathway-finder/blob/master/pathway-to-mirna-mappings.json

**Comment by AlexanderPico** [comment]
Good news: Skipped the dummy file and just made the real thing! I just committed the csv table:
https://github.com/ariutta/mirna-pathway-finder/blob/master/wp-mir-table-hs.csv
together with a readme that describes its construction and columns, and other build materials:
https://github.com/ariutta/mirna-pathway-finder/tree/master/wp-mir-table-builder

Bad news: I couldn't do it in a way that preserves a pathway element reference per mirtarbase ID, so we can't do highlighting this round. Let's save that for a future feature.

**Comment by ariutta** [comment]
@AlexanderPico, do we want to highlight all the Entrez Gene ids listed when displaying a pathway?

**Comment by AlexanderPico** [comment]
We can't in this version... unless you mean to highlight every Entrez Gene listed in the lookup table, in which case, no, we don't want to do that.

In a future version, it would be nice to highlight the mirnas on the pathways that overlap with the query list, plus the genes on the pathway that overlap with the target list from TIF run on the query list.

**Comment by ariutta** [comment]
For the search functionality, do we want return all results matching `mhits` and/or `mthits`?

**Comment by AlexanderPico** [comment]
Let's have 3 result columns of hit counts per pathway: miRNAs, miRNA targets, total. And then sort by total. Researchers can then choose to focus/ignore counts per their use case without having to know it ahead of time, e.g., look selectively at pathways with miRNAs.

**Comment by ariutta** [comment]
OK. Re-closing...
