### ISSUE TITLE
Improve database build process

### ISSUE THREAD

**Issue by khanspers** [ariutta/mirna-pathway-finder#6]
With the latest miRTarBase update (may 2016), the db build process takes close to 5 days to complete (on 16 GB RAM). Database file size has increased from ~500kb to 2.9MB. Should consider making database building script (R) more efficient, or consider including interactions with strong evidence only. As an example, stats for the TIF database are:

All interactions: 17470 nodes and 322379 edges
Filtered for non-weak interactions only: 2705 nodes and 5490 edges

**Comment by AlexanderPico** [comment]
Fixed with new build process:
https://github.com/nrnb/mirna-pathway-finder/tree/master/new-table-builders
