### ISSUE TITLE
Add mapping for MIMAT IDs

### ISSUE THREAD

**Issue by ariutta** [ariutta/mirna-pathway-finder#7]
Some pathways use Ensembl and others use MIMAT IDs. Our current code only considers the ones annotated with Ensembl, but we should also consider the ones annotated with MIMAT IDs.

**Comment by AlexanderPico** [comment]
MIMATs either should not be used by pathway authors, or they should be added to BridgeDb.  If in BridgeDb, then the gmt files would have them converted to Entrez. Either way, the PF tool only needs to work with Entrez IDs.
